all:
	gcc -o readfile -g readfile.c
	gcc -o writefile -g writefile.c 
	gcc -o mycp -g mycp.c
	gcc -o mystrcpy -g mystrcpy.c
	gcc -o fdreadfile -g fdreadfile.c 
	gcc -o mycp_with_child -g mycp_with_child.c 
	gcc -o mmap -g mmap.c

clean:
	rm -f readfile writefile mycp mystrcpy fdreadfile mycp_with_child mmap
